-- MySQL Script generated by MySQL Workbench
-- sáb 12 may 2018 19:40:38 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuenta` (
  `idcuenta` INT NOT NULL,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  `totalDebe` DECIMAL(4,4) NULL,
  `totalHaber` DECIMAL(4,4) NULL,
  `saldoInicial` DECIMAL(4,4) NULL,
  `saldoFinal` DECIMAL(4,4) NULL,
  PRIMARY KEY (`idcuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`almacenMP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`almacenMP` (
  `idalmacenMP` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `noOrden` INT NULL,
  `noPiezasEntrada` INT NULL,
  `noPiezasSalida` INT NULL,
  `noPiezasExistencia` INT NULL,
  `costoUnitario` DECIMAL(4,4) NULL,
  `debe` DECIMAL(4,4) NULL,
  `haber` DECIMAL(4,4) NULL,
  `saldo` DECIMAL(4,4) NULL,
  `cuenta_idcuenta` INT NOT NULL,
  PRIMARY KEY (`idalmacenMP`, `cuenta_idcuenta`),
  INDEX `fk_almacenMP_cuenta_idx` (`cuenta_idcuenta` ASC),
  CONSTRAINT `fk_almacenMP_cuenta`
    FOREIGN KEY (`cuenta_idcuenta`)
    REFERENCES `mydb`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`almacenPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`almacenPT` (
  `idalmacenPT` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `noPiezasEntrada` INT NULL,
  `noPiezasSalida` INT NULL,
  `noPiezasExistencia` INT NULL,
  `costoMedio` DECIMAL(4,4) NULL,
  `debe` DECIMAL(4,4) NULL,
  `salida` DECIMAL(4,4) NULL,
  `almacenMP_idalmacenMP_noCuenta` INT NOT NULL,
  `almacenMP_cuenta_idcuenta` INT NOT NULL,
  PRIMARY KEY (`idalmacenPT`, `almacenMP_idalmacenMP_noCuenta`, `almacenMP_cuenta_idcuenta`),
  INDEX `fk_almacenPT_almacenMP1_idx` (`almacenMP_idalmacenMP_noCuenta` ASC, `almacenMP_cuenta_idcuenta` ASC),
  CONSTRAINT `fk_almacenPT_almacenMP1_noCuenta`
    FOREIGN KEY (`almacenMP_idalmacenMP_noCuenta` , `almacenMP_cuenta_idcuenta`)
    REFERENCES `mydb`.`almacenMP` (`idalmacenMP` , `cuenta_idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimiento` (
  `idmovimiento` INT NOT NULL,
  `debe` DECIMAL(4,4) NULL,
  `haber` DECIMAL(4,4) NULL,
  `cuenta_idcuenta` INT NOT NULL,
  PRIMARY KEY (`idmovimiento`, `cuenta_idcuenta`),
  INDEX `fk_movimiento_cuenta1_idx` (`cuenta_idcuenta` ASC),
  CONSTRAINT `fk_movimiento_cuenta1`
    FOREIGN KEY (`cuenta_idcuenta`)
    REFERENCES `mydb`.`cuenta` (`idcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
